---
#
- name: Check deploymentclient.conf exists and is configured
  ansible.builtin.template:
    src: "deploymentclient.j2"
    dest: "{{ splunk.hmdir }}/etc/system/local/deploymentclient.conf"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0640
...
