---
# deploy and configure honeypot node
- name: Playbook
  hosts: honeypots
  become: yes
  tasks:
    - name: Uninstall SplunkForwarder
      ansible.builtin.include_role:
        name: splunk_uf
        tasks_from: remove-splunkuf.yml
...
